apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-credit-rating
  labels:
    app: bian-customer-credit-rating
    service-domain: customer-credit-rating
spec:
  selector:
    matchLabels:
      app: bian-customer-credit-rating
  template:
    metadata:
      labels:
        app: bian-customer-credit-rating
        service-domain: customer-credit-rating
    spec:
      serviceAccountName: bian-binding-service-sa
      containers:
        - name: business-ccr
          image: quay.io/ruben/bian-credit-rating:latest
          ports:
            - containerPort: 10001
              name: inbound
        - name: binding-service
          image: quay.io/ruben/bian-binding-service:latest
          env:
            - name: MERCURY_SERVICEDOMAIN
              value: customer-offer
          ports:
            - containerPort: 10100
              name: outbound
            - containerPort: 10101
              name: internal
---
apiVersion: v1
kind: Service
metadata:
  name: customer-credit-rating-binding
  labels:
    app: bian-customer-credit-rating
    service-domain: customer-credit-rating
    mercury-binding: internal
spec:
  ports:
    - port: 10101
      protocol: TCP
      name: internal
  selector:
    app: bian-customer-credit-rating
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-offer
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
spec:
  selector:
    matchLabels:
      app: bian-customer-offer
  template:
    metadata:
      labels:
        app: bian-customer-offer
        service-domain: customer-offer
    spec:
      serviceAccountName: bian-binding-service-sa
      containers:
        - name: business-co
          image: quay.io/ruben/bian-customer-offer:latest
          ports:
            - containerPort: 10001
              name: inbound
            - containerPort: 8080
              name: http
        - name: binding-service
          image: quay.io/ruben/bian-binding-service:latest
          env:
            - name: MERCURY_SERVICEDOMAIN
              value: customer-offer
          ports:
            - containerPort: 10100
              name: outbound
            - containerPort: 10101
              name: internal
---
apiVersion: v1
kind: Service
metadata:
  name: customer-offer-binding
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
    mercury-binding: internal
spec:
  ports:
    - port: 10101
      protocol: TCP
      name: internal
  selector:
    app: bian-customer-offer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-offer-http
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
    mercury-binding: external
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: bian-customer-offer